name: Known Issue
description: Track an issue already identified in the baseline (from docs/issues)
labels: [bug]
body:
  - type: dropdown
    id: known_issue
    attributes:
      label: Select Known Issue
      description: Choose an existing known issue stub from `docs/issues/`
      options:
        - Debug panel is always visible
        - Messages are not persisted on reload
        - AI and Storage toggles do not affect backend functionality
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      description: Add any details, observations, or links
